### ISSUE TITLE
Shaders with CRLF line endings build/bundling bug

### ISSUE THREAD

**Issue by FlexYourBrain** [defold/defold#9681]
**Description:**
Using the new shader pipeline with SPIR-v compatible GLSL code that has CRLF line endings causes errors when building or bundling html5 or bundling projects from windows.

1. Using minimal repro case below open project and build to html5 or bundle. * Have only tested from windows machines.

**Expected behavior**
Expected to be able to build/bundle projects with new shader pipeline using any line endings. e.g. `.gitattributes` set to `* text=auto`

**Defold version:**
  - Version 1.9.4

**Platforms (REQUIRED):**
 - Platforms:  Windows, HTML5
 - OS: Windows 10 / 11

**Minimal repro case project:**
[CRLF_line_endings.zip](https://github.com/user-attachments/files/17600764/CRLF_line_endings.zip)

**Error :**
```ruby
/assets/materials/vertex_color.fp
    build/default_html5/assets/materials/vertex_color.fpc:\Users\∙‼╢\AppData\Local\Temp\vertex_color.fpc17606850436492460685.glsl
ERROR: C:\Users\∙‼╢\AppData\Local\Temp\vertex_color.fpc17606850436492460685.glsl:2: '#version' : must occur first in shader 
ERROR: C:\Users\∙‼╢\AppData\Local\Temp\vertex_color.fpc17606850436492460685.glsl:2: '#version' : bad profile name; use es, core, or compatibility 
ERROR: C:\Users\∙‼╢\AppData\Local\Temp\vertex_color.fpc17606850436492460685.glsl:2: '#version' : bad tokens following profile -- expected newline 
ERROR: C:\Users\∙‼╢\AppData\Local\Temp\vertex_color.fpc17606850436492460685.glsl:2: '' : compilation terminated 
ERROR: 4 compilation errors.  No code generated.


ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link
```

**Workaround:**
Convert project to LF line endings , e.g. in ` .gitattributes `  ` * text eol=lf `
